[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rewars_srv"

[dependencies]
shared = { path = "../shared" }
rena = { path = "../../rena" }
tracing = "0.1"
tracing-subscriber = "0.3"
