[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
alkahest = { git = "https://github.com/zakarumych/alkahest", tag = "v0.2.0-rc.6", features = ["derive"]}
tracing = "0.1"
tracing-subscriber = "0.3"
